name: Pull request Pipeline

on:
  pull_request:
    branches: 
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install
        uses: actions/setup-node@v2
        with:
          node-version: 14.18
        run: yarn

      - name: Build
        run: yarn build